### ISSUE TITLE
unrecognized import path "libguestfs.org/guestfs"

### ISSUE THREAD

**Issue by supermomonga** [zchee/docker-machine-xhyve#17]
```sh
❯ go version
go version go1.5.1 darwin/amd64

❯ brew install libguestfs --devel --env=std
Warning: zchee/libguestfs/libguestfs-1.31.7 already installed
```

then, I tried to make docker-machine-xhyve, but shows following error when run `go get` and `make`.

```sh
❯ go get -d github.com/zchee/docker-machine-xhyve
package libguestfs.org/guestfs: unrecognized import path "libguestfs.org/guestfs"

❯ cd $GOPATH/src/github.com/zchee/docker-machine-xhyve

❯ make
==> Build docker-machine-xhyve ...
 go build -o bin/docker-machine-driver-xhyve -ldflags  -w -s -X github.com/zchee/docker-machine-xhyve/version.GitCommit=7b49bbd  github.com/zchee/docker-machine-xhyve/bin 
# github.com/zchee/docker-machine-xhyve/vendor/libguestfs.org/guestfs
vendor/libguestfs.org/guestfs/guestfs.go:31:10: fatal error: 'guestfs.h' file not found
#include "guestfs.h"
         ^
1 error generated.
make: *** [build] Error 1
```

I wrote `export GO15VENDOREXPERIMENT=1` to my `.zshrc` and retried, then `go get` shows no errors, but `make` shows same error.

**Comment by supermomonga** [comment]
## update

I applied write permission to some directories so get `guestfs.h` linking works.

```sh
sudo chown $(whoami):admin /usr/local && sudo chown -R $(whoami):admin /usr/local
brew unlink libguestfs && brew link libguestfs
```

( Note: I think this problem came with El Capitan's `rootless` feature. )

Then, `go get -d github.com/zchee/docker-machine-xhyve` works fine, without no unrecognized import warning!

Next step, I tried to make it but same error was shown.

```sh
❯ make
==> Build docker-machine-xhyve ...
 go build -o bin/docker-machine-driver-xhyve -ldflags  -w -s -X github.com/zchee/docker-machine-xhyve/version.GitCommit=605fba6  github.com/zchee/docker-machine-xhyve/bin 
# github.com/zchee/docker-machine-xhyve/vendor/libguestfs.org/guestfs
vendor/libguestfs.org/guestfs/guestfs.go:31:10: fatal error: 'guestfs.h' file not found
#include "guestfs.h"
         ^
1 error generated.
make: *** [build] Error 1
```

I tried `CGO_CFLAGS="-DGUESTFS_PRIVATE=1 -I/usr/local/include" CGO_LDFLAGS="-L/usr/local/lib -lguestfs" godep go build -i -o ./bin/docker-machine-driver-xhyve ./bin`, and it seems crated `docker-machine-driver-xhyve` executable into `bin` dir.

I think maybe options for `go build` like `-ldflags` causes something wrong.
Could you show me what options is suitable for replacement those environment variable?
I tried `-ldflags` and `-cflags`, but not sure it's right way and failed to build.

```sh
❯ go build -o bin/docker-machine-driver-xhyve -ldflags "-L /usr/local/lib" -gcflags "-I /usr/local/include" github.com/zchee/docker-machine-xhyve/bin 
# github.com/zchee/docker-machine-xhyve/vendor/libguestfs.org/guestfs
/Users/momonga/.go/src/github.com/zchee/docker-machine-xhyve/vendor/libguestfs.org/guestfs/guestfs.go:31:10: fatal error: 'guestfs.h' file not found
#include "guestfs.h"
         ^
1 error generated.
```

## working pattern

I edit `Makefile` and found a working pattern.

https://github.com/zchee/docker-machine-xhyve/blob/7b49bbd5f11ef5481cf20715d4a9b08eb7d80ebf/Makefile#L108-L109

```Makefile
CGO_CFLAGS:=${CGO_CFLAGS} -I /usr/local/include
CGO_LDFLAGS:=${CGO_LDFLAGS} -L /usr/local/lib
```

- `:=` instead of `=` to avoid recursive variable reference
- add a whitespace after `-I` and `-L`

https://github.com/zchee/docker-machine-xhyve/blob/7b49bbd5f11ef5481cf20715d4a9b08eb7d80ebf/Makefile#L144

```Makefile
	CGO_CFLAGS="${CGO_CFLAGS}" CGO_LDFLAGS="${CGO_LDFLAGS}" ${GO_BUILD} -ldflags "${CGO_LDFLAGS}" ${GO_GCFLAGS} ${TOP_PACKAGE_DIR}/${PACKAGE}/bin || exit 1
```

- add `CGO_CFLAGS` and `CGO_LDFLAGS` re-definition. (It's weird. Why re-definition make it works?)

**Comment by zchee** [comment]
@supermomonga Oh...
I terrible mistake.

I understand all. and I did not have enough knowledge to write a `Makefile`.

I will fix for now.
Thanks!!

**Comment by supermomonga** [comment]
I found that #19 pull request removes `libguestfs` dependency, so I think this build problem is also resolved.

**Comment by zchee** [comment]
and, https://github.com/zchee/docker-machine-xhyve/commit/0a9b453cd249e47c1079661552d6fc72f37b5e27

Thanks @supermomonga !!
