### ISSUE TITLE
unrecognized import path "libguestfs.org/guestfs"

### ISSUE THREAD

**Issue by akram** [zchee/docker-machine-xhyve#2]
Hi,
thank you for this great work.
I have a an issue when trying to compile docker-machine-xhyve
When trying to  
```
go get  github.com/zchee/docker-machine-xhyve
```
I have the following error:
```
package libguestfs.org/guestfs: unrecognized import path "libguestfs.org/guestfs"
```
despite I ran previously and successfully:
```
 brew install libguestfs --with-go --devel --env=std
```

**Comment by saratovsource** [comment]
This is a go v5.x feature. Package in `vendor` project path...
Before compile try to set ENV like
```
export GO15VENDOREXPERIMENT=1
```

**Comment by akram** [comment]
oh perfect
I did not noticed it thanks

**Comment by zchee** [comment]
Thanks @saratovsource :)
