### ISSUE TITLE
Shared folders

### ISSUE THREAD

**Issue by johanneswuerbach** [zchee/docker-machine-xhyve#20]
Maybe implement a first prototype using NFS? Looks like OS X and b2d ships everything required already https://gist.github.com/mattes/4d7f435d759ca2581347

**Comment by zchee** [comment]
@johanneswuerbach Yes, I knew.
FYI, https://github.com/ailispaw/boot2docker-xhyve this repo also implement `nfs`.

but, tiborvass said https://github.com/docker/machine/pull/1358#issuecomment-113985627.
I think so too.

The hard way to achieve the shared folder without `nfs`.
For the need of `nsf`users, I think that it is good as a substitute for until implement.

However, I do not require a shared folder use docker...
So, I have no intention of writing code for now :(
