### ISSUE TITLE
No vendored dependencies

### ISSUE THREAD

**Issue by nathanleclaire** [zchee/docker-machine-xhyve#7]
The Makefile and everything uses Godeps but the dependencies are not vendored there.

**Comment by zchee** [comment]
Hi @nathanleclaire 

Sorry, I actually do not know well the `godep`...
What does it mean in particular?

**Comment by zchee** [comment]
@nathanleclaire About libguestfs/guestfs?

**Comment by nathanleclaire** [comment]
Usually the required libraries are bundled alongside the code inside of `Godeps`.  For instance, take a look at the Machine source code.  Inside of `Godeps/_workspace/src` there are all the packages we depend on.  I haven't been able to successfully compile your code from the instructions here so far.

**Comment by zchee** [comment]
@nathanleclaire Oh, I missed!

I use the `godep` only to the management of package vendoring for `docker-machine-xhyve`.
but, I had a misunderstanding that `godep go build` using the `GO15VENDOREXPERIMENT=1`.

I think How to solve this problem...

1. Put `GO15VENDOREXPERIMENT=1` to `Makefile`, like docker-machine
2. Symlink `vendor` to `Godeps/_workspace/src` for not set `GO15VENDOREXPERIMENT=1` user or Go 1.4 or previous.
3. Move `vendor` to `Godeps/_workspace/src`, and symlink `Godeps/_workspace/src` to `vendor` for `GO15VENDOREXPERIMENT=1` user.

Which do you think is correct?

===

BTW, 

> Inside of Godeps/_workspace/src there are all the packages we depend on.

Do `Godeps/_workspace/src` exists in the docker-machine?
https://github.com/docker/machine/tree/master/Godeps

**Comment by zchee** [comment]
@nathanleclaire 
The `Godeps/_workspace/src` does not exist, I was referring to the structure of the docker-machine

**Comment by nathanleclaire** [comment]
Ah, OK, you have that `vendor` directory -- didn't see that.  In that case it might be sufficient to set `GO15VENDOREXPERIMENT=1` in Makefile.

**Comment by nathanleclaire** [comment]
With that setting I can compile the binary properly but running into a variety of other issues.
